CREATE DATABASE IF NOT EXISTS PROJETO_SMARTCOFFEE;
USE PROJETO_SMARTCOFFEE;

CREATE TABLE IF NOT EXISTS CLIENTES (
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60),
CPF VARCHAR(11),
EMAIL VARCHAR(100),
DATA_NASCIMENTO DATE,
TELEFONE VARCHAR(15) 
);

CREATE TABLE IF NOT EXISTS  PAGAMENTOS(
ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
FORMA_PAGAMENTO VARCHAR (30),
VALOR FLOAT,
DATA_PAGAMENTO DATE,
STATUS_PAGAMENTO ENUM ('ATIVO'),
INFORMACOES_PAGAMENTO VARCHAR(20) 
);

CREATE TABLE IF NOT EXISTS DELIVERY (
ID_DELIVERY INT AUTO_INCREMENT PRIMARY KEY,
TEMPO_ENTREGA TIME,
CLIENTE VARCHAR(60),
FORMA_PAGAMENTO VARCHAR(50),
TAMANHO_PEDIDO VARCHAR(40),
ENDERECO VARCHAR(30) 
);

CREATE TABLE IF NOT EXISTS PEDIDOS (
ID_PEDIDO INT AUTO_INCREMENT PRIMARY KEY,
QUANTIDADE VARCHAR(50),
DATA_PEDIDO DATE,
PRODUTOS_PEDIDOS VARCHAR(20),
VALOR FLOAT,
NUMERO_PEDIDO INT 
);

CREATE TABLE IF NOT EXISTS  PRODUTOS (
ID_PRODUTO INT AUTO_INCREMENT PRIMARY KEY,
LOTE_PRODUTO DATETIME,
VALIDADE DATE,
ESTOQUE VARCHAR(30),
VALOR FLOAT,
QUANTIDADE INT 
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
ID_FUNCIONARIO INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60),
SALARIO FLOAT,
TELEFONE VARCHAR(11),
DATA_NASCIMENTO DATE,
CARGO VARCHAR(40) 
);

CREATE TABLE IF NOT EXISTS ESTOQUE (
ID_ESTOQUE INT AUTO_INCREMENT PRIMARY KEY,
DATA_ENTRADA DATE,
QUANTIDADE VARCHAR(40),
ITENS_ESTOQUE VARCHAR(50),
LOTE FLOAT,
STATUS_ESTOQUE ENUM ('DISPONIVEL') 
);

CREATE TABLE IF NOT EXISTS PROGRAMA_DE_FIDELIDADE (
ID_FIDELIDADE INT AUTO_INCREMENT PRIMARY KEY,
VALOR FLOAT,
TEMPO_ASSINATURA DATETIME,
DADOS_CLIENTE VARCHAR(40),
TERMOS TEXT,
ASSINATURA TEXT 
);
