CREATE DATABASE IF NOT EXISTS SESI_EXTENSAOVSTA;

USE SESI_EXTENSAOVSTA;

SHOW TABLES;

-- VISULAIZAR TODOS OS BD
SHOW SCHEMAS;

CREATE TABLE IF NOT EXISTS ALUNOS (
    ID_ALUNO INT AUTO_INCREMENT PRIMARY KEY,
    NOME_ALUNO VARCHAR(60) NOT NULL,
    CPF_ALUNO CHAR(11) NOT NULL UNIQUE,
    DATA_NASCIMENTO DATE NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);

-- VISUALIZAR INFORMAÇÕES SOBRE OS DADOS DA TABELA 
DESCRIBE ALUNOS;