-- COMANDO PARA CRIAR UM BANCO DE DADOS 
CREATE DATABASE ESCOLA_CHICO;
CREATE DATABASE ESCOLA_CHICO2;

-- COMANDO PARA APAGAR UM BANCO DE DADOS
DROP DATABASE ESCOLA_CHICO2; 

-- COMANDO PARA ATIVAR BANCO DE DADOS 
USE ESCOLA_CHICO; 

-- CRIAR TABELAS 
CREATE TABLE ALUNOS (
ID_ALUNO INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
DATA_NASCIMENTO DATE NOT NULL,
TELEFONE VARCHAR(15) NOT NULL,
ENDERECO VARCHAR(100) NOT NULL,
STATUS_CLIENTE CHAR(10) DEFAULT "ATIVO",
DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE PROFESSORES (
ID_PROFESSOR INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
EMAIL VARCHAR (50) NOT NULL UNIQUE,
CADASTRO_DATA TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE COORDENACAO(
ID_ESCOLA INT AUTO_INCREMENT PRIMARY KEY,



);


-- COMANDO PARA APAGAR TABELAS
DROP TABLE CLIENTES;