-- PROJETO SMARTCOFFEE CHICO

-- CRIAR BANCO DE DADOS
-- ATIVAR BANCO DE DADOS
-- CRIAR TABELAS

-- OPCIONAIS NO DIA 21/08/2026
-- INSERIR DADOS
-- CONSULTAR DADOS 

-- ---------------------------------------------------------------------------------

CREATE DATABASE IF NOT EXISTS SMARTCOFFEE;
USE SMARTCOFFEE;

CREATE TABLE IF NOT EXISTS CLIENTE (
EMAIL VARCHAR(60),
NOME VARCHAR(60)
);

CREATE TABLE IF NOT EXISTS PEDIDOS (
OBSERVACAO TEXT,
DATA_PEDIDO DATETIME
);

CREATE TABLE IF NOT EXISTS AVALIACAO (
ID_AVALIACAO INT AUTO_INCREMENT PRIMARY KEY,
NOTAS TEXT
);

CREATE TABLE IF NOT EXISTS ESTOQUE (
ID_ESTOQUE INT AUTO_INCREMENT PRIMARY KEY,
QUANTIDADE TEXT
);
