-- COMANDOS PARA CRIAR BD 
-- 1
CREATE DATABASE GESTAO_ESCOLAR_CHICO;
CREATE DATABASE IF NOT EXISTS GESTÃO_ESCOLAR_CHICO;

CREATE DATABASE BANCO_DADOS;CREATE DATABASE BANCO_DADOS


-- ATIVAR BD E ATUALIZAR SCHEMAS
-- 2
USE GESTAO_ESCOLAR_CHICO;

-- CRIAR TABELAS
-- 4
CREATE TABLE IF NOT EXISTS COORDENAÇAO (
ID_ESCOLA INT AUTO_INCREMENT PRIMARY KEY,
NOME_ALUNOS VARCHAR (60) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
DATA_NASCIMENTO DATE NOT NULL,
EMAIL VARCHAR(100),
TELEFONE VARCHAR(15),
MATRICULA ENUM ('SIM', 'NÃO') NOT NULL
);

CREATE TABLE IF NOT EXISTS FUNCIONARIOS (
ID_FUNCIONARIO INT PRIMARY KEY,
NOME_FUNCIONARIO VARCHAR(60) NOT NULL,
CPF VARCHAR(14) NOT NULL UNIQUE,
TELEFONE VARCHAR(15),
SALARIO DECIMAL(5,2) NOT NULL DEFAULT 0.00 
);
 

-- ALTERAR INFORMAÇÕES DA TABELA
-- ALTER TABLE 
-- ADICIONAR UM CAMPO (ATRIBUTO) OU COLUNA NA TABELA
ALTER TABLE FUNCIONARIOS ADD EMAIL VARCHAR(100) NOT NULL;

-- ALTERAR TIPO DE DADOS DE CAMPO (ATRIBUTO) OU COLUNA NA TABELA
ALTER TABLE FUNCIONARIOS MODIFY EMAIL VARCHAR(50) NOT NULL;

-- APAGAR O CAMPO ATRIBUTO OU COLUNA NA TABELA
ALTER TABLE FUNCIONARIOS DROP COLUMN EMAIL;

-- RENOMEAR TABELAS
RENAME TABLE FUNCIONARIOS TO FUNCIONARIOSS;
RENAME TABLE FUNCIONARIOSS TO FUNCIONARIOS;

-- APAGAR DADOS DA TABELA
TRUNCATE TABLE ALUNOS;

-- APAGAR BD
DROP DATABASE GESTAO_ESCOLAR_CHICO;

-- APAGAR TABELAS
DROP TABLES FUNCIONARIOS;

-- MOSTRAR TABELAS NO BD
SHOW TABLES;


------------------------------------------

-- INSERIR DADOS NO BD
INSERT INTO FUNCIONARIOS (ID_FUNCIONARIO,NOME_FUNCIONARIO,CPF,TELEFONE,SALARIO)
VALUES(1,'CHICO','487490098-42','(19)99922-0375',999),
(3, 'LUCCAS','251.123.456-78','(19)91239-0123',300);

-- CONSULTAR DADOS NO BD
SELECT * FROM FUNCIONARIOS;


-- MOSTRAR TODOS OS DB
SHOW DATABASES;


INSERT INTO FUNCIONARIOS(ID_FUNCIONARIO,NOME_FUNCIONARIO,CPF,TELEFONE,SALARIO)
VALUES (2, 'CHICO','487.490.098-42','19 99922-0375',200)
-- PADRÃO PARA DATA ANO-MÊS-DIA

CREATE TABLE IF NOT EXISTS ALUNOS (
RM_ALUNOS INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60),
CPF INT,
ANO_LETIVO VARCHAR(25),
STATUS_ALUNO ENUM ('ATIVO'


)
