CREATE DATABASE OFICINA_CHICO;
USE OFICINA_CHICO;

CREATE TABLE IF NOT EXISTS CLIENTES (
ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
ORCAMENTO FLOAT,
CPF VARCHAR (11),
DATA_NASCIMENTO DATE,
TELEFONE VARCHAR(9),
NOME VARCHAR(60)
);

CREATE TABLE FUNCIONÁRIOS (
ID_FUNCIONÁRIO INT AUTO_INCREMENT PRIMARY KEY,
CARGO VARCHAR(10),
SALARIO FLOAT,
DATA_NACIMENTO DATE,
CPF VARCHAR (11),
NOME VARCHAR(60)
);

CREATE TABLE VEICULOS (
ID_VEÍCULO INT AUTO_INCREMENT PRIMARY KEY,
TIPO_VEÍCULO VARCHAR(10),
PLACA FLOAT,
ANO_VEICULO DATE,
COR VARCHAR (20),
PECAS VARCHAR(10)
);

CREATE TABLE SERVICOS (
ID_SERVICO INT AUTO_INCREMENT PRIMARY KEY,
AGENDAMENTO VARCHAR(20),
STATUS_SERVICO  ENUM ('ATIVO', 'INATIVO') NOT NULL,
TERMOS TEXT,
ORCAMENTO VARCHAR(20),
PECAS VARCHAR(10)
);

CREATE TABLE MODELOS (
ID_MODELO INT AUTO_INCREMENT PRIMARY KEY,
TIPO_MODELO VARCHAR(10),
FABRICAÇÃO DATE,
VALOR FLOAT,
NOME VARCHAR(20),
ORIGEM VARCHAR(10)
);

CREATE TABLE PAGAMENTOS (
ID_PAGAMENTO INT AUTO_INCREMENT PRIMARY KEY,
HORA_PAGAMENTO TIME,
ORCAMENTO VARCHAR(20),
VALOR FLOAT,
RECIBO VARCHAR(30),
TIPO_PAGAMENTO VARCHAR(10)
);

CREATE TABLE ORDENS_DE_SERVICO (
ID_ORDENS_SERVICO INT AUTO_INCREMENT PRIMARY KEY,
POLIMENTO VARCHAR(20),
CALIBRAGEM VARCHAR(30),
TROCA_PECAS VARCHAR(10),
REVISAO VARCHAR(20),
BALANCEAMENTO VARCHAR(40)
);

CREATE TABLE MARCAS (
ID_MARCA INT AUTO_INCREMENT PRIMARY KEY,
ANO_MARCA DATE,
MODELO VARCHAR (30),
TIPO_MARCA VARCHAR (20),
PAIS_ORIGEM VARCHAR(20),
NOME VARCHAR(60)
);

CREATE TABLE FORNECEDORES (
ID_FORNECEDOR INT AUTO_INCREMENT PRIMARY KEY,
NOME VARCHAR(60),
TIPO_FORNECEDOR VARCHAR(20),
DATA_NASCIMENTO DATE,
ENDERECO VARCHAR(30),
CNPJ VARCHAR(14)
);

CREATE TABLE PECAS (
ID_PECA INT AUTO_INCREMENT PRIMARY KEY,
QUANTIDADE VARCHAR(30),
TIPO_PECA VARCHAR(20),
ESTOQUE VARCHAR(40),
UNIDADE VARCHAR(20),
PRECO FLOAT
);

ALTER TABLE CLIENTES ADD EMAIL VARCHAR(100) NOT NULL;

ALTER TABLE FUNCIONARIOS ADD EMAIL VARCHAR(100) NOT NULL;

ALTER TABLE VEICULOS ADD STATUS_VEICULO VARCHAR(30) NOT NULL;

ALTER TABLE SERVICOS ADD DATA_SERVICO VARCHAR(50) NOT NULL;

ALTER TABLE MODELOS ADD TIPO_MOTOR VARCHAR(100) NOT NULL;

ALTER TABLE PAGAMENTOS ADD PIX VARCHAR(50) NOT NULL;

ALTER TABLE ORDENS_DE_SERVICO ADD TUNACAO VARCHAR(60) NOT NULL;

ALTER TABLE MARCAS ADD STATUS_MARCA VARCHAR(40) NOT NULL;

ALTER TABLE FORNECEDORES ADD EMAIL VARCHAR(100) NOT NULL;

ALTER TABLE PECAS ADD NUM_PECAS VARCHAR(100) NOT NULL;

RENAME TABLE FUNCIONÁRIOS TO FUNCIONARIOS;





ALTER TABLE FUNCIONARIOS DROP COLUMN EMAIL;

ALTER TABLE CLIENTES DROP COLUMN EMAIL;

ALTER TABLE VEICULOS DROP COLUMN STATUS_VEICULO;

ALTER TABLE SERVICOS DROP COLUMN DATA_SERVICO;

ALTER TABLE MODELOS DROP COLUMN TIPO_MOTOR;

ALTER TABLE PAGAMENTOS DROP COLUMN PIX;

ALTER TABLE ORDENS_DE_SERVICO DROP COLUMN TUNACAO;

ALTER TABLE MARCAS DROP COLUMN STATUS_MARCA;

ALTER TABLE FORNECEDORES DROP COLUMN EMAIL;

ALTER TABLE PECAS DROP COLUMN NUM_PECAS;